// frontend/src/pages/Home.tsx
import React from 'react';
import styled from 'styled-components';
import crossBoardImage from '../assets/images/cross-board.webp';

const HomeContainer = styled.div`
  width: 100%;
`;

const Section = styled.section`
  max-width: 1400px;
  margin: 0 auto;
  padding: 80px 20px;
  display: flex;
  align-items: center;
  gap: 80px;

  @media (max-width: 968px) {
    flex-direction: column;
    padding: 60px 20px;
  }
`;

const Content = styled.div`
  flex: 0.8;
  padding-left: 40px;
`;

const Title = styled.h1`
  font-size: 2.5rem;
  color: #1a237e;
  margin-bottom: 24px;
  font-weight: 600;
`;

const Description = styled.p`
  font-size: 1.1rem;
  line-height: 1.8;
  color: #424242;
  margin-bottom: 32px;
`;

const ImageContainer = styled.div`
  flex: 1.2;
  display: flex;
  justify-content: flex-end;
  align-items: center;
  overflow: hidden;
`;

const Image = styled.img`
  width: 100%;
  height: auto;
  object-fit: cover;
  border-radius: 4px;
`;

const ServicesSectionWrapper = styled.div`
  width: 100%;
  background-color: #f8f9fa;
`;

const ServicesSection = styled.section`
  max-width: 1400px;
  margin: 0 auto;
  padding: 80px 20px;
`;

const SectionTitle = styled.h2`
  font-size: 2.2rem;
  color: #1a237e;
  text-align: center;
  margin-bottom: 60px;
  font-weight: 600;
`;

const ServicesGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 24px;
  max-width: 1200px;
  margin: 0 auto;

  @media (max-width: 1024px) {
    grid-template-columns: repeat(2, 1fr);
    max-width: 800px;
    gap: 20px;
  }

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
    gap: 16px;
  }
`;

const ServiceCard = styled.div`
  background: white;
  padding: 24px;
  border-radius: 16px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.05);
  transition: all 0.3s ease;
  aspect-ratio: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;

  &:hover {
    transform: translateY(-5px);
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.1);
  }
`;

const IconContainer = styled.div`
  margin-bottom: 20px;

  svg {
    width: 40px;
    height: 40px;
    color: #2196f3;
  }
`;

const ServiceTitle = styled.h3`
  font-size: 1.2rem;
  color: #1a237e;
  margin-bottom: 12px;
  font-weight: 500;
`;

const ServiceDescription = styled.p`
  font-size: 0.95rem;
  line-height: 1.5;
  color: #424242;
  max-width: 220px;
`;

// 新的 SVG 图标
const MarketIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M21 11V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6"/>
    <path d="M9 22h6"/>
    <path d="M15 7v3"/>
    <path d="M9 7v3"/>
    <circle cx="18" cy="18" r="3"/>
    <path d="M18 14v1"/>
    <path d="M18 21v1"/>
    <path d="M22 18h-1"/>
    <path d="M15 18h-1"/>
  </svg>
);

const ProductIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>
    <path d="M3.3 7l8.7 5 8.7-5"/>
    <path d="M12 22V12"/>
  </svg>
);

const BrandIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/>
    <line x1="4" y1="22" x2="4" y2="15"/>
    <path d="M20 15v7"/>
    <path d="M12 12c2 0 5-1 5-1"/>
    <path d="M12 19c2 0 5-1 5-1"/>
  </svg>
);

const AIIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="2" y="3" width="20" height="14" rx="2" ry="2"/>
    <line x1="8" y1="21" x2="16" y2="21"/>
    <line x1="12" y1="17" x2="12" y2="21"/>
    <path d="M6 8h.01"/>
    <path d="M6 12h.01"/>
    <path d="M6 16h.01"/>
    <path d="M18 8h.01"/>
    <path d="M18 12h.01"/>
    <path d="M18 16h.01"/>
    <path d="M12 8v8"/>
    <path d="M8 12h8"/>
  </svg>
);

const Home: React.FC = () => {
  return (
    <HomeContainer>
      <Section>
        <Content>
          <Title>跨境全生态服务</Title>
          <Description>
            开拓全球电子商务市场
            <br /><br />
            我们帮助中国企业、制造商、贸易商和品牌商在美国、欧洲等海外市场成功拓展业务，实现产品出海和品牌国际化。
          </Description>
        </Content>
        <ImageContainer>
          <Image src={crossBoardImage} alt="跨境全生态服务" />
        </ImageContainer>
      </Section>

      <ServicesSectionWrapper>
        <ServicesSection>
          <SectionTitle>跨境优服</SectionTitle>
          <ServicesGrid>
            <ServiceCard>
              <IconContainer>
                <MarketIcon />
              </IconContainer>
              <ServiceTitle>市场洞察</ServiceTitle>
              <ServiceDescription>
                深入分析电商平台热销品类和消费者需求趋势。
              </ServiceDescription>
            </ServiceCard>

            <ServiceCard>
              <IconContainer>
                <ProductIcon />
              </IconContainer>
              <ServiceTitle>产品出海</ServiceTitle>
              <ServiceDescription>
                助力您的产品直接进入海外市场直达消费者，实现高效出海。
              </ServiceDescription>
            </ServiceCard>

            <ServiceCard>
              <IconContainer>
                <BrandIcon />
              </IconContainer>
              <ServiceTitle>品牌出海</ServiceTitle>
              <ServiceDescription>
                助力您的品牌在海外市场成功拓展，打造国际化形象。
              </ServiceDescription>
            </ServiceCard>

            <ServiceCard>
              <IconContainer>
                <AIIcon />
              </IconContainer>
              <ServiceTitle>AI 赋能运营</ServiceTitle>
              <ServiceDescription>
                利用AI工具赋能海外运营，实现数字化运营资产管理，提高效率和精准度。
              </ServiceDescription>
            </ServiceCard>
          </ServicesGrid>
        </ServicesSection>
      </ServicesSectionWrapper>
    </HomeContainer>
  );
};

export default Home;

// src/views/Home.vue
<template>
  <main>
    <section class="hero">
      <div class="hero-content">
        <h1>{{ t('hero.title') }}</h1>
        <p>{{ t('hero.subtitle') }}</p>
        <router-link to="/services" class="cta-button">
          {{ t('hero.cta') }}
        </router-link>
      </div>
    </section>

    <section id="services-overview" class="services-overview services-ai">
      <h2>{{ t('services.title') }}</h2>
      <div class="services-grid">
        <div v-for="service in services" :key="service.id" class="service-card">
          <div class="service-card-header" :style="{ background: service.gradient }"></div>
          <div class="service-card-content">
            <h3>{{ t(`services.items.${service.id}.title`) }}</h3>
            <p>{{ t(`services.items.${service.id}.description`) }}</p>
            <router-link :to="service.link" class="learn-more">
              {{ t('services.learnMore') }}
            </router-link>
          </div>
        </div>
      </div>
    </section>

    <section class="how-it-works">
      <h2>{{ t('competencies.title') }}</h2>
      <p class="subtitle-underline">{{ t('competencies.subtitle') }}</p>
      <div class="steps">
        <div v-for="step in competencies" :key="step.id" class="step">
          <div class="step-icon">
            <i :class="step.icon"></i>
          </div>
          <h3>{{ t(`competencies.items.${step.id}.title`) }}</h3>
          <p>{{ t(`competencies.items.${step.id}.description`) }}</p>
        </div>
      </div>
    </section>

    <section class="samples">
      <div class="container">
        <h2>{{ t('cases.title') }}</h2>
        <div class="samples-grid">
          <div v-for="sample in cases" :key="sample.id" class="sample-card">
            <img :src="sample.image" :alt="t(`cases.items.${sample.id}.title`)" />
            <div class="sample-content">
              <h3>{{ t(`cases.items.${sample.id}.title`) }}</h3>
              <p>{{ t(`cases.items.${sample.id}.description`) }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const services = [
  {
    id: 'crossBorder',
    gradient: 'linear-gradient(to right, #3b82f6, #60a5fa)',
    link: '/services#cross-border'
  },
  {
    id: 'aiEmpowerment',
    gradient: 'linear-gradient(to right, #10b981, #34d399)',
    link: '/services#ai-empowerment'
  },
  {
    id: 'marketResearch',
    gradient: 'linear-gradient(to right, #f59e0b, #fbbf24)',
    link: '/services#market-research'
  }
]

const competencies = [
  {
    id: 'expertise',
    icon: 'fas fa-users'
  },
  {
    id: 'ai',
    icon: 'fas fa-robot'
  },
  {
    id: 'global',
    icon: 'fas fa-globe'
  }
]

const cases = [
  {
    id: 'case1',
    image: new URL('@/assets/images/case1.webp', import.meta.url).href
  },
  {
    id: 'case2',
    image: new URL('@/assets/images/case2.webp', import.meta.url).href
  },
  {
    id: 'case3',
    image: new URL('@/assets/images/case3.webp', import.meta.url).href
  }
]
</script>

<style lang="scss" scoped>
.hero {
  height: 100vh;
  background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),
    url('@/assets/images/hero-bg.webp') no-repeat center center;
  background-size: cover;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  color: #fff;
  margin-top: -4rem;
}

.hero-content {
  max-width: 800px;
  padding: 2rem;

  h1 {
    font-size: 3rem;
    margin-bottom: 1rem;
  }

  p {
    font-size: 1.5rem;
    margin-bottom: 2rem;
  }
}

.cta-button {
  display: inline-block;
  padding: 1rem 2rem;
  background-color: #3b82f6;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  transition: background-color 0.3s;

  &:hover {
    background-color: #2563eb;
  }
}

.services-overview {
  padding: 4rem 2rem;
  background-color: #f9fafb;

  h2 {
    text-align: center;
    margin-bottom: 3rem;
  }
}

.services-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.service-card {
  background-color: #fff;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  transition: transform 0.3s;

  &:hover {
    transform: translateY(-5px);
  }
}

.service-card-header {
  height: 150px;
}

.service-card-content {
  padding: 2rem;

  h3 {
    margin-bottom: 1rem;
  }

  p {
    color: #666;
    margin-bottom: 1.5rem;
  }
}

.learn-more {
  color: #3b82f6;
  text-decoration: none;
  font-weight: 500;

  &:hover {
    text-decoration: underline;
  }
}

.how-it-works {
  padding: 4rem 2rem;
  text-align: center;

  h2 {
    margin-bottom: 1rem;
  }

  .subtitle-underline {
    color: #666;
    margin-bottom: 3rem;
    position: relative;
    display: inline-block;

    &:after {
      content: '';
      position: absolute;
      bottom: -0.5rem;
      left: 50%;
      transform: translateX(-50%);
      width: 50px;
      height: 2px;
      background-color: #3b82f6;
    }
  }
}

.steps {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.step {
  padding: 2rem;

  .step-icon {
    font-size: 2.5rem;
    color: #3b82f6;
    margin-bottom: 1rem;
  }

  h3 {
    margin-bottom: 1rem;
  }

  p {
    color: #666;
  }
}

.samples {
  padding: 4rem 2rem;
  background-color: #f9fafb;

  h2 {
    text-align: center;
    margin-bottom: 3rem;
  }
}

.samples-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.sample-card {
  background-color: #fff;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);

  img {
    width: 100%;
    height: 200px;
    object-fit: cover;
  }
}

.sample-content {
  padding: 1.5rem;

  h3 {
    margin-bottom: 0.5rem;
  }

  p {
    color: #666;
  }
}

@media (max-width: 768px) {
  .hero-content {
    h1 {
      font-size: 2rem;
    }

    p {
      font-size: 1.2rem;
    }
  }

  .services-grid,
  .steps,
  .samples-grid {
    grid-template-columns: 1fr;
  }
}
</style>
